languageCode: en-us
title: Invasive Pedals
baseURL: 'https://hugo-theme-massively.netlify.com/'
theme: massively
googleanalytics: ''
disqusShortname: 'invasivepedals'
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
languages:
  en:
    languageName: English
