languageCode: en-us
title: Invasive Pedals
baseURL: 'http://localhost:1313/'
theme: massively
googleanalytics: ''
disqusShortname: invasivepedals
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
languages:
  en:
    languageName: English
